title: Sea Dogs 1
page.title: Sea Dogs 2
page.title: Sea Dogs 3
description: Group 18
show_downloads: true
logo: assets/Logo.png

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme
